[build]
  command   = "npm run web-build"
  publish   = "web-build"            
  functions = "netlify/functions"    

[functions]
  node_bundler          = "esbuild"
  external_node_modules = ["node-fetch"]
