[build]
  command   = "expo build:web"
  publish   = "web-build"

[functions]
  directory              = "netlify/functions"
  node_bundler           = "esbuild"
  external_node_modules  = ["node-fetch"]
